server {
    listen 80;

    # Use Kubernetes DNS (CoreDNS)
    resolver 10.96.0.10 valid=30s ipv6=off;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/ {
    rewrite ^/api/(.*)$ /$1 break;

    proxy_pass http://backend-service:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
}

